### ISSUE TITLE
Implement testing

### ISSUE THREAD

**Issue by caloisio** [1757WestwoodRobotics/2022-RapidReact#9]
Testing is an essential aspect of good Engineering/Development practice. The robustness, performance, and overall quality of our code will improve if we include regular testing as a part of our process.

### Proposed Definitions
`testing`: verifying that the implementation of a component performs as-designed
`unit testing`: testing the component in isolation
`integration testing`: testing the component in conjunction with the overall system
`performance testing (benchmarking)`: measuring a metric of a component or system

### Tasks
- [ ] Investigate how to implement unit, integration, and performance tests in a robotpy-based project
- [ ] Implement a testing framework
- [ ] Configure the github project to run and validate tests on code-change
- [ ] *Optional:* Configure the github project to track the result of performance tests over time

**Comment by agelsomini** [comment]
This should be considered a relatively high priority item for the off season.  With Dustin's changes this year the robotpy test frameworks are at least partially running.  We should be able to write tests for both modules in isolation and things that interact with the HAL.

One area that we should definitely focus on is providing example tests that test the state transitions as that seems to be a place where we have had issues.
